[project]
name = "mcbe-chinese-patch"
version = "0.2.0"
description = "Minecraft: Bedrock Edition Chinese Language Patch Tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "orjson>=3.9.0",
    "qiling>=1.4.6",
]
